version: "3"
services:

  conquest:
    image: zhonger/ubuntu:latest
    container_name: dev
    environment:
     - GITHUB_NAME=zhonger
    stdin_open: true
    tty: true
    volumes:
     - ~/web/test:/home/ubuntu/test
    restart: always